### ISSUE TITLE
Broken schema

### ISSUE THREAD

**Issue by fsmaia** [getsentry/sentry-api-schema#45]
The API Schema is broken and I cannot generate API clients using [OpenAPI generator](https://openapi-generator.tech/).

Even if I skip validation I'm getting a fatal exception, as shown on [this workflow](https://github.com/fsmaia/sentry-apigen/actions/runs/5267792248/jobs/9523520545#step:4:375).

Fixing this is the first step for automating API client generation, which would aggregate much value for Sentry users.

### Environment

MacOS Ventura 13.3.1 with ZShell

### Steps to Reproduce

1. Clone the repository
2. Run [OpenAPI generator](https://openapi-generator.tech/) validation for the OpenAPI Schema file:
   ```bash
   npx @openapitools/openapi-generator-cli validate -i openapi-defered.json
   ```

### Expected Result

Validation should be successful

### Actual Result

```
Errors:
	- attribute
	  paths.'/organizations/{organization_slug}/releases/{version}/deploys/'(post).requestBody.content.'application/json'.schema.items
	  is missing
Warnings:
	- Unused model: MonitorValidator
	- Unused model: ConfigValidator
	- Unused model: SCIMListResponseEnvelopeSCIMTeamIndexResponse
	- Unused model: MonitorAlertRuleTargetValidator
	- Unused model: MonitorCheckIn
	- Unused model: Monitor
	- Unused model: OrganizationEventsResponseDict
	- Unused model: TeamSCIM
	- Unused model: SCIMListResponseEnvelopeSCIMMemberIndexResponse
	- Unused model: SCIMTeamPatchOperation
	- Unused model: OutcomesResponse
	- Unused model: SCIMTeamPatchRequest
	- Unused model: MonitorList
	- Unused model: OrganizationMemberWithRoles
	- Unused model: SCIMPatchRequest
	- Unused model: MonitorCheckInValidator
	- Unused model: OrganizationMemberSCIM
	- Unused model: SourceMapDebug
	- Unused model: SCIMMemberProvision
	- Unused model: SCIMPatchOperation
	- Unused model: SCIMTeamRequestBody
	- Unused model: CheckInList
	- Unused model: MonitorAlertRuleValidator
	- Unused model: OrganizationProjectResponseDict

[error] Spec has 1 errors.
```

**Comment by schew2381** [comment]
Hi! I just deployed the fix for this so it should be safe to revert back to pulling the schema from https://raw.githubusercontent.com/getsentry/sentry-api-schema/main/openapi-derefed.json
